/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Conexion;
import Clases.Inventario;
import static Frames.Interfaz.jcbDepartamento;
import static Frames.Interfaz.jtxtCodigo;
import static Frames.Interfaz.jtxtCosto;
import static Frames.Interfaz.jtxtDescripcion;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author hajoc
 */
public class nuevoDepartamento extends javax.swing.JFrame {

    public nuevoDepartamento() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    
    void insertarDepartamento(){
        if(!jtxtDepartamento.getText().isEmpty()){
            Conexion.queryExecute("INSERT INTO departamento(nombre_departamento) "
                            + "VALUES('"+jtxtDepartamento.getText()+"');");
            JOptionPane.showMessageDialog(null,"Departamento agregado");
            Inventario.cargarDepartamentos();
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Ingresa el nombre del departamento");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDepartamentos = new javax.swing.JPanel();
        jpOpcInventario4 = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        btnGuardarDepartamento = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        btnCancelarDepartamento = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jtxtDepartamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpDepartamentos.setBackground(new java.awt.Color(250, 250, 250));
        jpDepartamentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpDepartamentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpOpcInventario4.setBackground(new java.awt.Color(250, 250, 250));
        jpOpcInventario4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator11.setForeground(new java.awt.Color(153, 153, 153));
        jpOpcInventario4.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 10));

        btnGuardarDepartamento.setBackground(new java.awt.Color(250, 250, 250));
        btnGuardarDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarDepartamentoMouseClicked(evt);
            }
        });
        btnGuardarDepartamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(7, 131, 213));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("Guardar");
        btnGuardarDepartamento.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 20));

        jLabel84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Save_24px_3.png"))); // NOI18N
        btnGuardarDepartamento.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jpOpcInventario4.add(btnGuardarDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 140, -1));

        jSeparator12.setForeground(new java.awt.Color(153, 153, 153));
        jpOpcInventario4.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 10));

        btnCancelarDepartamento.setBackground(new java.awt.Color(250, 250, 250));
        btnCancelarDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarDepartamentoMouseClicked(evt);
            }
        });
        btnCancelarDepartamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel72.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(7, 131, 213));
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Cancelar");
        btnCancelarDepartamento.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, 20));

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Back_24px.png"))); // NOI18N
        btnCancelarDepartamento.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jpOpcInventario4.add(btnCancelarDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, -1));

        jpDepartamentos.add(jpOpcInventario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 340, 80));

        jtxtDepartamento.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jpDepartamentos.add(jtxtDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 300, 30));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 100, 100));
        jLabel1.setText("Nombre del departamento");
        jpDepartamentos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 230, 20));

        getContentPane().add(jpDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarDepartamentoMouseClicked
        insertarDepartamento();
    }//GEN-LAST:event_btnGuardarDepartamentoMouseClicked

    private void btnCancelarDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarDepartamentoMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarDepartamentoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCancelarDepartamento;
    private javax.swing.JPanel btnGuardarDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JPanel jpDepartamentos;
    private javax.swing.JPanel jpOpcInventario4;
    private javax.swing.JTextField jtxtDepartamento;
    // End of variables declaration//GEN-END:variables
}
